language: java
jdk:
  - oraclejdk9
os:
  - linux
sudo: false
branches:
  only:
    - master
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
addons:
  apt:
    packages:
      - oracle-java9-installer
before_script:
  - chmod +x gradlew
script:
  - ./gradlew -version
  - ./gradlew clean check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
